SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE 
    (GENOTYPE & 2) = 0 
    AND (GENOTYPE & 5) > 0;


# SELECT COUNT(*) AS COUNT
# FROM ECOLI_DATA
# WHERE BIN(GENOTYPE) = '1' 
#     OR BIN(GENOTYPE) LIKE '%101' 
#     OR BIN(GENOTYPE) LIKE '%100'
#     OR BIN(GENOTYPE) LIKE '%001'