WITH RECURSIVE ECOLI_GEN AS (
    -- 1. Base Case: 1세대(최초의 대장균) 정의
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 2. Recursive Step: 부모와 자식을 연결하여 세대(GENERATION) 증가
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN ECOLI_GEN G 
      ON E.PARENT_ID = G.ID
)

-- 3. 자식이 없는 개체 필터링 및 세대별 집계
SELECT COUNT(G.ID) AS COUNT, 
       G.GENERATION
FROM ECOLI_GEN G
LEFT JOIN ECOLI_DATA CHILD 
  ON G.ID = CHILD.PARENT_ID
WHERE CHILD.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION ASC;